name: hamagon
description: Pest identification app.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase core
  firebase_core: ^0.4.0+9

    # Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.11.1+3
  google_sign_in: ^4.0.7
  cloud_firestore: ^0.12.9+4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # To pick image
  image_picker: ^0.6.1+4

  # ml vision
  # firebase_ml_vision: ^0.9.2+2
  # firebase_livestream_ml_vision: ^1.0.1
  # tflite
  # tflite: ^1.0.4

  automl_mlkit:
    path: ../automl_mlkit/

  path_provider: ^0.5.0+1

  url_launcher: ^5.1.4

  # Text search
  algolia: ^0.1.6+1

  # For sign in
  rxdart: ^0.22.2

  # Datetime format
  intl: ^0.16.0


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/images/bug.jpg
    - assets/images/news-icon.png
    - assets/images/avatar-placeholder.png
    - assets/images/hamagon-logo.png
    - assets/images/google_logo.png
    - assets/images/farmland.jpg
    - assets/dict.txt
    - assets/model.tflite
    - assets/manifest.json
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
